language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  api_key:
    secure: 5a2jTxGYuNC13tcupZQx4/sZVUbhY7Wtq5q3LsI2+MKHKymJInm5w8TQtKIr/9gkXvqWkMjUy4/jx/YEYRtpde4jaz62NaZVkPlO9HB/eLHjFZ/YuUgJE0sbBeBAFM7Um9OTTriWEKQuuLVK/VGsB0jZ472Fv1ZR1g1+QBgdM27ISLF6sb3wNxDrmWQiHGKleixT9IIWPxHp+e3l2pGbIcRVQt4mtta5DjTo1aQWR3RNWWM3UuqZy3XYZuc74kDKmhDCxBF2vxvuvgT882yhKQX/+iI99dOtX1YFmF/torOS/Xid179L+S77XdgutFqPqJfdgZ+Hx0T/5JJVevG41e6Hz1WJER7eUFdXqkdKgKSClvo7kMo5l07Wv6weSRLSqq/ipC1dC6IoKZX5tHXQ1cR24qmtJB5MmEYDhXjlvCyhVf+/pyA9hnCoL8dbK+6ahXRbMiujpOPa8r6K3yYQqab3hsLUQOxfckA23zKiRHIhTn5O1Xwu8K93mr56cPM95GsWR/2dc1XMbOswYpbjhS2V2uZjdrFUXBy5RbD7DgXAmhrpGYC4OUXDO2VGSycH91A9iTcTGvRyffW/driCYykcwKU8vf/lQNHm8G1dwZVmsa3V3WGrRapBI4lkIDIiSHuvu6dD6HNlPgpoD6hQnk5okKp1fLeKwreElilJFQ0=
